[phases.setup]
nixPkgs = ["python311Full", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "python3.11 -m pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py"
